Outlier detection
automl/HPOBench pull request #111
Opened 2021-07-06 10:54 UTC by renesass

2021-07-07 09:39 UTC, renesass commented
Always get the following error:
`ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-l87z2mi1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-l87z2mi1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mzyxrsqx
         cwd: /tmp/pip-req-build-l87z2mi1/
    Complete output (1 lines):
    error in hpobench setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`

2021-07-07 09:58 UTC, renesass commented
Container creation was successful but getting
`FATAL:   container creation failed: mount error: can't mount image /proc/self/fd/8: failed to mount squashfs filesystem: input/output error`
now.

2021-07-08 06:58 UTC, PhMueller commented
Hey, 
I will try it. Singularity is sometimes a little bit hard to handle. :-) 

Also, the PR looks pretty good, but one question: Your Checkpoint Callback saves the model to which directory? 

Cheers, Philipp

2021-07-08 08:16 UTC, renesass commented
CheckpointSaver does not save the model but the weights. The weights are saved locally within the class, and thus, no file will be written.

2021-07-14 12:36 UTC, KEggensperger requested changes
Made a first pass. Looks good, but the objective values need to be double-checked and be better described. Thank already.

2021-07-14 12:36 UTC, KEggensperger commented on extra_requirements/outlier_detection.json
> +  "outlier_detection": ["torch==1.9.0", "pytorch_lightning==1.3.8", "scikit-learn==0.24.2", "scipy==1.7.0"]
Is there a specific feature you need from scipy=1.7.0?
Scipy>=1.4.1 is already installed for HPOBench, see [here](https://github.com/automl/HPOBench/blob/master/requirements.txt) (and probably scikit-learn and pytorch will require it as well). Would it be possible to remove it from this list?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/backbones/mlp.py
> +import torch
This is not directly benchmark code. Could you move all code that doe not contain classes inheriting from AbstractBenchmark to `od_utils/`?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/backbones/mlp.py
> +import torch
Same for the other files below

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +        dataset_name : str
Please add a list with allowed dataset names

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +        Training ends if validation AUPR is not getting better after 10 epochs.
Is this "area under the PR curve", could you please add that? Also, the benchmark should return something to be minimized, so this is probably misleading?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +            function_value : validation AUPR
Same here, is this "1- mean validation AUPR"?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +                train_loss : training loss
And this is then "1-X" as well or is it the actual aupr value (or even the real loss value)?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +    Hyperparameter optimization task to optimize an autoencoder
This would be the right location for some more details, e.g. what you sent me:

A fully connected autoencoder implemented in PyTorch Lightning~\cite{falcon2019pytorch} with a maximum of four layers (including latent layer) is optimized on AUPR. In addition to the neural architecture hyperparameters, the benchmark includes multiple regularization techniques, scalers, and activation functions to train the autoencoder on 15 different Outlier Detection DataSets~\cite{rayana2016}\footnote{annthyroid, arrhytmia, breastw, cardio, ionosphere, mammography, musk, optdigits, pendigits, pima, satellite, satimage-2, thyroid, vowels, wbc}. Cross-validation, early stopping, and the number of training epochs as fidelity complete the benchmark.

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +            train_loss = 1 - model.train_losses[index]
Please double check this.

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +            trainer.fit(
Can this fail, e.g. not converge? If yes, then this should be surrounded by a try/catch and return 1 (or whatever is the highest for your metric)

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +                'train_loss': float(np.mean(np.array(model.train_losses))),
This also wants to be double checked to be consistent with above (here, you don't do 1-loss)

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +        dropout_rate = CSH.UniformFloatHyperparameter('dropout_rate', 0, 0.8, default_value=0.5)
So, theorethically dropout can be turned off by setting it to 0 although it is turned on?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +        choice = CSH.CategoricalHyperparameter(
If there's only one optimizer, then this hyperparameter is constant and not necessary.

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +        for optimizer, hyperparameters in optimizers.items():
same here

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +        batch_size = CSH.UniformIntegerHyperparameter('batch_size', lower=16, upper=512, default_value=128)
looks like it should be on a log scale?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +            CS.UniformIntegerHyperparameter("epochs", lower=10, upper=100, default_value=10, log=False),
default should be the highest value, i.e. 100

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +            'references': [
Please add what this reference is for

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_kde.py
> +    for outlier detection.
Also here, some more details are necessary for someone new to understand what this benchmark is doing

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/trad_benchmark.py
> +            function_value : validation loss
Please also make sure that this is described correctly and returns the correct value

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ocsvm.py
> +        return OneClassSVM(kernel="rbf", gamma=hp_gamma, nu=hp_nu)
is there a way to set the seed?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ocsvm.py
> +        return OneClassSVM(kernel="rbf", gamma=hp_gamma, nu=hp_nu)
same question for all models

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/trad_benchmark.py
> +        shuffle : bool
this is not imlemented and should be removed

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/trad_benchmark.py
> +        train_loss = 1 - self.calculate_aupr(model, X_train, y_train)
Also, shouldn't this be the same code as for the network solution?

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/benchmarks/od/trad_benchmark.py
> +        dataset_fraction: float - [0.1, 1]
not implemented

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/container/recipes/od/Singularity.ODAutoencoder
> +    && git checkout master \
development for now

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/container/recipes/od/Singularity.ODKernelDensityEstimation
> +    && git checkout master \
development for now

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/container/recipes/od/Singularity.ODOneClassSupportVectorMachine
> +    && git checkout OutlierDetection \
development for now

2021-07-14 12:36 UTC, KEggensperger commented on hpobench/util/od_data_manager.py
> +    openml_task_id : int
openml is not involved here?

2021-07-15 08:08 UTC, renesass commented on extra_requirements/outlier_detection.json
> +  "outlier_detection": ["torch==1.9.0", "pytorch_lightning==1.3.8", "scikit-learn==0.24.2", "scipy==1.7.0"]
removed it

2021-07-15 08:13 UTC, renesass commented on hpobench/benchmarks/od/backbones/mlp.py
> +import torch
I created a new folder hpobench/dependencies/od.
Makes sense to have such a folder also for other benchmarks in the future. Let me know what you think.

2021-07-15 08:26 UTC, renesass commented on hpobench/benchmarks/od/od_ae.py
> +        Training ends if validation AUPR is not getting better after 10 epochs.
it returns something to be minimized, just didn't mention it properly in the description.

2021-07-15 08:41 UTC, renesass commented on hpobench/benchmarks/od/od_ae.py
> +            function_value : validation AUPR
you are completely right. I changed all of that. Sorry that I didn't see that in the first place.

2021-07-15 08:53 UTC, renesass commented on hpobench/benchmarks/od/od_ae.py
> +            trainer.fit(
good point. thanks for pointing out!

2021-07-15 08:57 UTC, renesass commented on hpobench/benchmarks/od/od_ae.py
> +        dropout_rate = CSH.UniformFloatHyperparameter('dropout_rate', 0, 0.8, default_value=0.5)
set it to 0.2

2021-07-15 09:00 UTC, renesass commented on hpobench/benchmarks/od/od_ae.py
> +        batch_size = CSH.UniformIntegerHyperparameter('batch_size', lower=16, upper=512, default_value=128)
why should batch_size be on log scale?

2021-07-15 09:02 UTC, renesass commented on hpobench/benchmarks/od/od_ae.py
> +            'references': [
what do you mean?

2021-07-15 09:04 UTC, renesass commented on hpobench/benchmarks/od/od_ocsvm.py
> +        return OneClassSVM(kernel="rbf", gamma=hp_gamma, nu=hp_nu)
Unfortunately not. Neither OCSVM nor KDE provides an option for a seed.

2021-07-15 09:13 UTC, renesass commented on hpobench/benchmarks/od/trad_benchmark.py
> +        train_loss = 1 - self.calculate_aupr(model, X_train, y_train)
the network is trained on the reconstruction distance. However, I added train_aupr too.

2021-07-15 09:20 UTC, renesass commented on hpobench/benchmarks/od/trad_benchmark.py
> +        train_loss = 1 - self.calculate_aupr(model, X_train, y_train)
I removed it again. Since the training data are mostly clean datapoints, it makes no sense to calculate the train aupr.

2021-07-15 09:29 UTC, renesass commented on hpobench/benchmarks/od/trad_benchmark.py
> +        train_loss = 1 - self.calculate_aupr(model, X_train, y_train)
I added it again and set the contamination ratio to 10%.

2021-07-30 14:20 UTC, PhMueller commented on hpobench/benchmarks/od/backbones/mlp.py
> +import torch
Fine by me. I have placed it for the TurBO-Benchmarks into `utils/benchmarks/....`. 
But we can also call it dependencies.

2021-07-30 14:55 UTC, KEggensperger approved these changes
Looks good to me, but I'll leave it up to @PhMueller to merge this eventually.

2021-07-30 14:55 UTC, KEggensperger commented on hpobench/benchmarks/od/od_ae.py
> +        batch_size = CSH.UniformIntegerHyperparameter('batch_size', lower=16, upper=512, default_value=128)
I guess, it doesn't have to. I believe I've seen it more often optimized on a logscale. If you've optimized it like that for your work, it's fine by me.

2021-07-30 17:14 UTC, PhMueller commented
It works now. 
I will now rebase the branch onto the current dev branch.

2021-07-30 17:16 UTC, PhMueller approved these changes
I will upload the benchmark container to the registry.

2021-08-04 15:10 UTC, merged