Raw YAHPO Benchmarks
automl/HPOBench pull request #153
Opened 2022-05-25 15:50 UTC by PhMueller

Interface to evaluate the true performance of a configuration (not as surrogate or tabular benchmark)

2022-05-27 09:36 UTC, KEggensperger requested changes

2022-05-27 09:36 UTC, KEggensperger commented on extra_requirements/rbv2.json
> +  "rbv2_old": ["yahpo_gym@git+https://github.com/pfistfl/yahpo_gym#egg=yahpo_gym&subdirectory=yahpo_gym", "rpy2", "numpy", "configspace", "pandas==1.2.4","scikit-learn==0.24.2", "openml==0.10.2"]
there are missing dependency versions

2022-05-27 09:36 UTC, KEggensperger commented on hpobench/container/recipes/ml/Singularity.rbv2Benchmark
> +    && echo "Please never push a recipe that checks out any other branch than development or master" \
This contradicts the next line where you checkout a different branch ...

2022-09-15 09:50 UTC, LGro commented on hpobench/util/data_manager.py
> +            self.logger.info(f'Successfully cloned data from repo to {self.data_dir}')
Given that `yahpo_data` is licensed under [AGPL](https://github.com/slds-lmu/yahpo_data/blob/main/LICENSE), how do you judge the compatibility with this repo's more permissive Apache-2.0 license, @KEggensperger and @PhMueller?

2022-09-20 07:16 UTC, LGro commented on hpobench/util/data_manager.py
> +            self.logger.info(f'Successfully cloned data from repo to {self.data_dir}')
And the maintainers over there just [relicensed to Apache-2.0](https://github.com/slds-lmu/yahpo_data/commit/f9b8cd24fd8e7d9cc8fb7372f9640128941255e5). My question is resolved then, I think :relaxed:

2023-02-22 08:57 UTC, merged