Make installable for Python 3.10.6
automl/HPOBench pull request #155
Opened 2022-08-09 21:59 UTC by dwoiwode

Due to [following line](https://github.com/automl/HPOBench/blob/d8b45b1eca9a61c63fe79cdfbe509f77d3f5c779/setup.py#L39), HPOBench is no installable for Python 3.10.6. I use HPOBench in the test cases of my package ([pyPDPPartitioner](https://github.com/dwoiwode/py-pdp-partitioner)) and therefore need to install HPOBench in the test-pipeline. This fails, as this line prohibits the installation.

There are a few workarounds for me:
1. Change `python_requires='>=3.6, <=3.10'` to `python_requires='>=3.6, <3.11'`, which just stalls the issue (Currently done in this branch)
2. Remove upper python boundary so that `python_requires='>=3.6, <=3.10'` will be `python_requires='>=3.6'`
3. Remove HPOBench in my test cases/dependencies

Personally, I do not think there is an issue with the second approach, although this might be untested in future python versions

2022-08-10 10:35 UTC, eddiebergman commented
I think approach 2. is best, there's rarely ever a reason to upper bound a python version

2022-08-10 15:28 UTC, PhMueller commented
Hi, 

thanks for your pull request.
Approach 2 is also fine by me.

Could you also please redirect the PR to the development branch?

Thanks

2022-08-10 15:30 UTC, PhMueller requested changes

2022-08-10 15:30 UTC, PhMueller commented on setup.py
> +    python_requires='>=3.6, <3.11',
```suggestion
    python_requires='>=3.6',
```

2022-08-11 10:05 UTC, dwoiwode commented
Looks like the python versions were interpreted as floats instead of strings. I hope the latest commit fixes this

2022-08-29 06:14 UTC, PhMueller commented
I think the build for python 3.10 crashes due some old (unnecessary) dependencies that we have in the HPOBench.
We are planing to remove them with the next release (coming end of september). This should fix the error above. 
We also will include the support for py>=3.10 then.

2022-08-29 09:15 UTC, eddiebergman commented
We have a similar issue in auto-sklearn, the problem is essentially the scikit learn version. Scikit learn needs an older version of numpy which doesn't release a pre-built wheel for python 3.10. Therefore, it downloads the older version of numpy and tries to build it for python 3.10 and then fails.

2022-09-28 09:15 UTC, PhMueller commented
Hey, thanks for your work. I have fixed the remaining error in #155 on our side and included your changes into the dev branch. 

Therefore, i close this PR.

2022-09-28 09:15 UTC, closed without merging