Nasbench201
automl/HPOBench pull request #37
Opened 2020-08-19 10:54 UTC by PhMueller

Consecutive Pull Request after #36. 

This pull request contains the code for the nasbench201 benchmark.

The data for this benchmark will be downloaded by the start of the benchmark. The download function is thread-safe!

2020-08-19 17:31 UTC, PhMueller commented
This does not fail on travis:
[![Build Status](https://travis-ci.org/PhMueller/HPOlib3.svg?branch=Nasbench201)](https://travis-ci.org/PhMuellerl/HPOlib3)

2020-08-20 10:29 UTC, KEggensperger approved these changes

2020-08-21 12:43 UTC, KEggensperger requested changes

2020-08-21 12:43 UTC, KEggensperger commented on hpolib/benchmarks/nas/nasbench_201.py
> +                'cost': float(np.mean(train_times) * epoch),
Could you please return here the actual sum of the training epochs? I realized that there are indeed different runtimes per configuration per epoch (they only slightly vary, but they vary).

Also, if you return the mean across N seeds, the runtime should also reflect the total runtime of training N networks

2020-08-25 12:45 UTC, PhMueller commented
Sorry, didn't see that merge coming. :smile: 
The test will fail because the new image is still uploading to singularity. I saved a commit to trigger travis later when it is uploaded. 

The next commit will solve everything :smile:

2020-08-26 14:34 UTC, KEggensperger approved these changes

2020-08-26 14:35 UTC, merged